### ISSUE TITLE
Malformed packet crashes server

### ISSUE THREAD

**Issue by lawl** [pion/turn#40]
### Your environment.
  - Version: 1.0.3 from https://github.com/pion/turn/releases/download/1.0.3/simple-turn-linux-amd64
  - Browser: n/a
  - Other Information 

```
panic: runtime error: index out of range

goroutine 1 [running]:
encoding/binary.bigEndian.Uint16(...)
        /usr/local/go-d2c7dec183f0da628abf16848e9e92987feebe32/src/encoding/binary/binary.go:100
github.com/pions/pkg/stun.getChannelLength(...)
        /go/src/github.com/pions/pkg/stun/channel_data.go:40
github.com/pions/pkg/stun.NewChannelData(0xc000012600, 0x2, 0x5dc, 0x1, 0x0, 0x0)
        /go/src/github.com/pions/pkg/stun/channel_data.go:23 +0x161
github.com/pions/turn/internal/server.(*Server).handleUDPPacket(0xc000056100, 0xc00000c1c0, 0xc00000c1e0, 0xc000012600, 0x5dc, 0x5dc, 0x2, 0xc00006c870, 0x0)
        /go/src/github.com/pions/turn/internal/server/server.go:76 +0xc0
github.com/pions/turn/internal/server.(*Server).Listen(0xc000056100, 0x5670ad, 0x7, 0xd96, 0x5dc, 0x5dc)
        /go/src/github.com/pions/turn/internal/server/server.go:65 +0x2e3
github.com/pions/turn.Start(0x582220, 0x6506e8, 0xc00001a0e6, 0x11, 0xd96)
        /go/src/github.com/pions/turn/turn.go:24 +0x178
main.main()
        /go/src/github.com/pions/turn/cmd/simple-turn/main.go:48 +0x2ec
```

### What did you do?

I was testing if the port is opened and crashed the TURN server. Oops. Very easy to repro

Start the server, in a different shell run:

    echo a | nc -u localhost 3478

### What did you expect?

Server gracefully handling malformed packets.

### What happened?

Server crashed, see stacktrace above.

**Comment by songjiayang** [comment]
Try again,  I test the latest version,  don't crash yet.

**Comment by Sean-Der** [comment]
This looks to have been fixed, if you are still having this issue please re-open. Thanks for using Pion TURN!

```
$ go run main.go -public-ip 127.0.0.1 -users foo=bar
turn ERROR: 2020/01/09 00:41:37 error when handling datagram: failed to create stun message from packet: unexpected EOF: not enough bytes to read header
turn ERROR: 2020/01/09 00:41:39 error when handling datagram: failed to create stun message from packet: unexpected EOF: not enough bytes to read header
turn ERROR: 2020/01/09 00:41:40 error when handling datagram: failed to create stun message from packet: unexpected EOF: not enough bytes to read header
turn ERROR: 2020/01/09 00:41:41 error when handling datagram: failed to create stun message from packet: unexpected EOF: not enough bytes to read header
turn ERROR: 2020/01/09 00:41:42 error when handling datagram: failed to create stun message from packet: unexpected EOF: not enough bytes to read header
```

```
$ echo a | nc -u localhost 3478
$ echo a | nc -u localhost 3478
$ echo a | nc -u localhost 3478
$ echo a | nc -u localhost 3478
$ echo a | nc -u localhost 3478
```
